name: "Setup Solana"
description: "Setup Solana"
runs:
  using: "composite"
  steps:
      - uses: actions/cache@v2
        name: Cache Solana Tool Suite
        id: cache-safecoin
        with:
          path: |
            ~/.cache/safecoin/
            ~/.local/share/safecoin/
          key: safecoin-${{ runner.os }}-v0000-${{ env.SOLANA_CLI_VERSION }}
      - run: sh -c "$(curl -sSfL https://release.safecoin.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
        shell: bash
      - run: echo "/home/runner/.local/share/safecoin/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - run: safecoin-keygen new --no-bip39-passphrase
        shell: bash
      - run: safecoin config set --url localhost
        shell: bash
